name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: checkdirectory
      run: pwd && ls 

    - name: cfn-lint
      uses: vetpartner/lambdatest@master 
      with:
        args: "**/*.yaml"
